package com.budget.modules.cxfInterface.wsdlclass;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "getTestInfoService", targetNamespace = "http://test.cmcc.com/getTestInfoService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetTestInfoService {

	/**
	 * 
	 * @param parameters
	 * @return returns test.SetTestInfoResponse
	 */
	@WebMethod(action = "getTestInfo")
	@WebResult(name = "setTestInfoResponse", targetNamespace = "http://test.cmcc.com/getTestInfoService", partName = "parameters")
	public SetTestInfoResponse getTestInfo(
			@WebParam(name = "getTestInfoRequest", targetNamespace = "http://test.cmcc.com/getTestInfoService", partName = "parameters") GetTestInfoRequest parameters);

}
